Repository ThunderTube/HyperTube, pull requests merged in 2020-03, with the labels that each got.

#17 Added github's OAuth strategy
  api/package.json
  api/src/config/passport.js
  api/src/controllers/auth.js
  api/src/models/User.js
  api/src/routes/auth.js
  api/yarn.lock
Labels: enhancement

#22 Added Google & Facebook OAuth strategies and fix some bug
  api/package.json
  api/src/config/passport.js
  api/src/controllers/auth.js
  api/src/index.js
  api/src/models/User.js
  api/src/routes/auth.js
  api/yarn.lock
Labels: enhancement, fix

#24 fix(auth): add process.env before FRONT_URI
  api/src/controllers/auth.js
Labels: fix

#25 Fix error with Facebook OAuth strategy
  api/src/config/passport.js
  api/src/routes/auth.js
Labels: fix

#29 Create movie page
  api/public/.gitignore
  api/src/controllers/auth.js
  api/src/controllers/stream.js
  api/src/get-movies.js
  api/src/models/Movie.js
  api/src/routes/auth.js
  api/src/routes/stream.js
  api/src/torrent.js
  app/src/App.vue
  app/src/components/AppButton.vue
  app/src/components/AuthScreen.vue
  app/src/components/EyeIcon.vue
  app/src/components/LazyMovieImage.vue
  app/src/components/ListDropdown.vue
  app/src/components/LoadingSpinner.vue
  app/src/components/MovieComment.vue
  app/src/components/MovieCommentsList.vue
  app/src/components/MoviePlayer.vue
  app/src/components/MovieStars.vue
  app/src/components/MovieThumbnail.vue
  app/src/components/MovieViewer.vue
  app/src/components/MovieViewerNoData.vue
  app/src/components/MoviesContainer.vue
  app/src/components/MoviesContainerEmptyList.vue
  app/src/components/MoviesSearchBar.vue
  app/src/components/MoviesSearchBarDropdown.vue
  app/src/components/MoviesSearchBarInput.vue
  app/src/components/NoData.vue
  app/src/components/PlayIcon.vue
  app/src/components/Tag.vue
  app/src/locales/en.json
  app/src/locales/fr.json
  app/src/router/index.js
  app/src/store/index.js
  app/src/store/modules/index.js
  app/src/utils.js
  app/src/views/Me.vue
  app/src/views/Movie.vue
  app/tailwind.config.js
  docker/api/Dockerfile.dev
Labels: enhancement

#38 Refractor some parts and fix bugs
  api/src/controllers/auth.js
  api/src/controllers/stream.js
  app/package.json
  app/public/index.html
  app/src/App.vue
  app/src/components/AppInput.vue
  app/src/components/AppMenu.vue
  app/src/components/AppSwitchLang.vue
  app/src/components/AuthScreen.vue
  app/src/components/MovieCommentsList.vue
  app/src/components/MovieThumbnail.vue
  app/src/locales/en.json
  app/src/locales/fr.json
  app/src/router/index.js
  app/src/store/index.js
  app/src/store/modules/auth/actions.js
  app/src/views/404.vue
  app/src/views/Auth.vue
  app/src/views/Home.vue
  app/src/views/OAuthError.vue
  app/yarn.lock
Labels: fix

#37 fix(auth): fix username regex
  api/src/models/User.js
Labels: fix

#39 Fix/update details
  app/src/components/AuthScreen.vue
  app/src/views/Me.vue
Labels: fix

#42 improvement(user-details): delete previous picture of user
  api/src/controllers/auth.js
Labels: enhancement

#41 Implement favorite language switcher and use it for subtitles
  api/src/controllers/auth.js
  api/src/controllers/stream.js
  api/src/models/User.js
  app/src/components/AuthScreen.vue
  app/src/components/MoviesSearchBarDropdown.vue
  app/src/locales/en.json
  app/src/locales/fr.json
  app/src/views/Me.vue
Labels: enhancement

#43 fix(oauth): add OAuth verif with ID & provider
  api/src/config/passport.js
  api/src/controllers/auth.js
  api/src/models/User.js
Labels: fix
